name: Docker

on: 
  workflow_dispatch:
    inputs:
      commitTag:
        description: 'Tag to checkout'
        required: true

jobs:
  docker-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commitTag }}
